### ISSUE TITLE
not building

### ISSUE THREAD

**Issue by lihshyang** [StanfordSNR/gg#14]
somehow `make` gives me this error:
...
...
make[3]: Entering directory `/home/aolx/devel/gg/src/util'
  CXX      digest.o
  CXX      util.o
  CXX      path.o
  CXX      pipe.o
  CXX      poller.o
  CXX      signalfd.o
digest.cc: In function ‘std::string digest::sha256(const string&, bool)’:
digest.cc:26:39: error: expected type-specifier before ‘Base64URLEncoder’
                                   new Base64URLEncoder( new StringSink( ret ), false ) ) );
                                       ^
digest.cc: In function ‘std::string digest::gghash_to_hex(const string&)’:
digest.cc:47:23: error: expected type-specifier before ‘Base64URLDecoder’
                   new Base64URLDecoder( new HexEncoder( new StringSink( output ), false ) ) );
                       ^
make[3]: *** [digest.o] Error 1

**Comment by sadjad** [comment]
You need `libcrypto++-dev` >= 4.5.3 to build gg. It's included in Ubuntu Zesty or newer, but for the others I think you need to build and install it from the source.
