### ISSUE TITLE
running fibonacci example

### ISSUE THREAD

**Issue by photoszzt** [StanfordSNR/gg#33]
Do I need to run upload.sh manually? I find that if I don't run that script, the code would prompt me saying V5tpA.GDOUdjLVlBznCj61Fi8HvqGhIcV67Ni3YvOkEE001bc520 (the hash of the add binary) is missing.

**Comment by photoszzt** [comment]
I'm not running on aws lambda. I'm porting the backend to openfaas. But the code is similar to what gcloud has.

**Comment by sadjad** [comment]
It's necessary for a subtle reason: normally, `gg` would automatically scan all the thunks at the start of the job, and will upload all of the necessary files in one shot to the storage backend. But, in the Fibonacci example, none of the initial thunks have the `add` binary -- it's gonna be in the thunks that are generated later.

However, I just made a small change to include `add` in the initial thunk, so running `upload.sh` is not necessary anymore.
