### ISSUE TITLE
S3 PUTs will fail if the x-amz-acl  header is set to "public-read"

### ISSUE THREAD

**Issue by kelleyma49** [StanfordSNR/gg#35]
Thank you for creating this intriguing and promising piece of software!

This issue might be similar to #20.

I get a 403 error in `S3Client::upload_files()` unless I remove the "x-amz-acl" header. I'm not an expert in S3 bucket permissions, but it looks to me as though gg requires public access to all S3 uploads? Maybe this should be configurable?

Here's the line in question:
https://github.com/StanfordSNR/gg/blob/be3f150d6011a8c5ac360304c7c2a358337cb89a/src/net/s3.cc#L39

**Comment by sadjad** [comment]
Hi @kelleyma49,

Thank you for bringing this into our attention! Actually, `gg` doesn't require public access for S3 objects, and that line is not necessary at all. I just pushed this change to `master`.

Please let me know if you encounter any other issues.

Best,
Sadjad
