### ISSUE TITLE
Building Chromium

### ISSUE THREAD

**Issue by wknapik** [StanfordSNR/gg#55]
Hi @sadjad. Could you share the code used to build Chromium? The paper mentions a custom setup with an ec2 instance. I'd like to give it a try, so anything you can share would be appreciated.

**Comment by sadjad** [comment]
Hi @wknapik -- take a look at `chrome` directory in `gg-results` repo. It contains the scripts for building Chromium: https://github.com/StanfordSNR/gg-results/tree/master/chrome

**Comment by wknapik** [comment]
Wow, that was fast ;] Thanks!

I'll give it a try tomorrow. Feel free to close this issue, but I'll probably have another question, or two...

**Comment by sadjad** [comment]
Sure thing!
